### PR TITLE
Removed extremely slow Array.prototype.slice from hot path

### PR DESCRIPTION
**Pull request by mcollina**
As titled :).

Where I am using this I got a a 10-20% throughput improvement with this change.

I'll ping you when I have something more solid on _where_ I am using this.

### CODE REVIEW

**Comment by yoshuawuyts** [comment]
This is great!

**Comment by yoshuawuyts** [comment]
Released as `v6.2.2` :tada: :tada: :tada: :tada:

**Comment by a0viedo** [comment]
@mcollina not seeing this in arbitrary big arrays (40M items) in latest versions of V8 ([issue](https://github.com/nodejs/benchmarking/issues/71)). I'll benchmark it in a few other engines and see what the results are.

**Comment by mcollina** [comment]
@a0viedo the problem is the use of `arguments`, not `slice()`. Your examples consider big arrays, but `arguments` is not an array.

**Comment by a0viedo** [comment]
oh I see!

**Pull request merged**
