### PR TITLE
emit: cache dft & no apply

### PR DESCRIPTION
**Pull request by yoshuawuyts**
- caches default routes
- removes `.apply()` calls

A bit more messy, but probably faster

related to #40

### CODE REVIEW

**Comment by yoshuawuyts** [comment]
cc/ @hughsk

**Comment by hughsk** [comment]
:clap: :tada:

**Comment by yoshuawuyts** [comment]
### pre patch benchmark
```txt
Running 10s test @ http://localhost:1337
  24 threads and 4000 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   740.99ms  401.90us 741.66ms   56.94%
    Req/Sec    16.76     34.83   166.00     92.68%
  745 requests in 10.11s, 518.43KB read
  Socket errors: connect 3757, read 0, write 0, timeout 673
Requests/sec:     73.70
Transfer/sec:     51.29KB
```
### post patch
```txt
Running 10s test @ http://localhost:1337
  24 threads and 4000 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    40.46ms    5.47ms 171.02ms   82.23%
    Req/Sec   713.56      1.33k    4.98k    87.26%
  56524 requests in 10.10s, 6.95MB read
  Socket errors: connect 3757, read 0, write 0, timeout 0
Requests/sec:   5595.78
Transfer/sec:    704.94KB
```

**Comment by hughsk** [comment]
Whoa that's a huge improvement, nice one! :grin:

**Comment by yoshuawuyts** [comment]
haha, not sure benchmarks hold up. I've changed more stuff. But hey, it's most likely better haha

**Comment by yoshuawuyts** [comment]
lol, ok it wasn't that. But hey, perf!

**Comment by yoshuawuyts** [comment]
I ran some other checks, and I don't believe this sped up things by a lot. Perhaps revisit later, but for now it's probably _good enough_

**Pull request closed without merging**
