### PR TITLE
create file getAllRoutes and add tests

### PR DESCRIPTION
**Pull request by wcastand**
A first try, what do you think about this implementation ?

I was thinking maybe add an object instead of a string to accès path and cb.
And maybe an object or array with the param keys.

### CODE REVIEW

**Comment by yoshuawuyts** [comment]
Sweet, nice work! I think an Object might indeed be valuable, as it allows for some interesting tricks. People can then get all routes from the object by using `Object.keys()`.

Small comment here though: as this is a low level package I'm cool if you use some ES6 in the tests, but none (except for `const`) in the actual implementation. This is due to a variety of reasons, amongst others due to compilation speed, legacy support and performance - but primarily for consistency with all the other packages I've written. Thanks for understanding! :sparkles:

**Comment by wcastand** [comment]
I update the PR, i'm not sure i did what you wanted so let me know if it's not what you had in mind :)
getAllRoutes returns an Object like this:
```javascript
{
  '/foo': function(x, y) { return x * y },
  '/foo/bar': function(x, y) { return x / y},
  '/bar/bchi': function(x, y) { return x%y}
}
```

i think i delete all the es6 stuff, but since i didn't write es5 for quite some time i'm not sure about what is es5 and es6 anymore :/

**Comment by wcastand** [comment]
I have no idea why is only testing my test file.
Help welcome on this :)

**Comment by yoshuawuyts** [comment]
odd, not sure why it's failing - perhaps try updating deps, running `node@4` and `node@6` in `.travis.yml`  hmmmm -if that fails try running it through `$ tap tests/*`

**Comment by yoshuawuyts** [comment]
implementation is looking good tho (:

**Comment by wcastand** [comment]
In local when i try npm run test. It does all the tests.
i update packages, i don't know if it works or why but cool lol

**Comment by yoshuawuyts** [comment]
hah, yeah it also works on my machine haha

**Comment by alexandrebodin** [comment]
Hi guys.

Hi after looking at your previous builds your cover script is at fault. 

Running `instabul cover test/*` is equivalent to running `node test/*` with cover which only runs one test file.

Until now all your coverage was only running the test `router.js`

To fix it you only need to do this in your package.json

```js
"test-cov": "NODE_ENV=test istanbul cover tape -- test/*"
```

Hope it helped ;)

Cheers

**Comment by wcastand** [comment]
es6 in test for walk.js break travis. I will correct them tomorrow

**Comment by yoshuawuyts** [comment]
Niceee - is this ready for review now?

**Comment by wcastand** [comment]
is it :)

**Comment by wcastand** [comment]
Do i need to do something here. Or you just didn't have the time to look at it ?
i'm just asking in case i missed something

**Comment by yoshuawuyts** [comment]
Thanks so much for this! - sorry for not merging earlier; been a bit low on bandwidth lately :sparkles:

**Comment by yoshuawuyts** [comment]
`v6.3.0` :sparkles:

**Pull request merged**
